# -*- encoding: utf-8 -*-

# ========================================================================
# Copyright and other protections apply. Please see the accompanying
# ``LICENSE`` and ``CREDITS`` files for rights and restrictions governing
# use of this software. All rights not expressly waived or licensed are
# reserved. If those files are missing or appear to be modified from their
# originals, then please contact the author before viewing or using this
# software in any capacity.
# ========================================================================

sudo: false
language: python

python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
    - "pypy"
    - "pypy3"

env:
    - DJANGO="1.8-lts"
    - DJANGO="1.11-lts"
    - DJANGO="2"
    - DJANGO="dev"

install:
    - pip install coveralls tox-travis

matrix:
    allow_failures:
        # PyPy3 is experimental
        - python: "pypy3"

        # Django dev is experimental
        - env: DJANGO="dev"

    exclude:
        - python: 2.7
          env: DJANGO="2"
        - python: 2.7
          env: DJANGO="dev"

script:
    - tox

after_success:
    - coveralls
